Updates nf_configs to use new, dedicated, .conf files.
  + Also removes file compression, the files are intentionally
    smaller now and uncompressed text allows git to do its work.

diff --git a/nf_configs b/nf_configs
--- a/nf_configs
+++ b/nf_configs
@@ -9,7 +9,7 @@
 #  A script for checking the output from the nftsim repo's .conf files
 #  against their expected test output. The expected/test output is stored in 
 #  the directory
-#    ./test/data/configs/
+#    ./test/numerical/data/
 #  The script also supports updating those expected output files when code or
 #  .conf file changes have been made that intentionally modify the output.
 #
@@ -84,8 +84,8 @@ msg_help(){
   printf '%s\n'   "    For example, to check the output of the 'example.conf' file, run:"
   printf '%s\n'   "        ./nf_configs --check 'example'"
   printf '%s\n'   "    or:"
-  printf '%s\n'   "        ./nf_configs --check './configs/example.conf'"
-  printf '%s\n'   "    or to check all configurations specified in the configs directory, run:"
+  printf '%s\n'   "        ./nf_configs --check './test/numerical/example.conf'"
+  printf '%s\n'   "    or to check all configurations specified in the test/numerical directory, run:"
   printf '%s\n'   "        ./nf_configs --check 'all'"
   printf '\n%s\n' "  --regenerate"
   printf '%s\n'   "    Regenerates the test output for the specified config file. This should ONLY be"
@@ -94,7 +94,7 @@ msg_help(){
   printf '%s\n'   "    committed as part of the pull request for the code changes that caused the"
   printf '%s\n'   "    output to change."
   printf '%s\n'   "    eg: ./nf_configs --regenerate 'example'"
-  printf '%s\n'   "    eg: ./nf_configs --regenerate './configs/example.conf'"
+  printf '%s\n'   "    eg: ./nf_configs --regenerate './test/numerical/example.conf'"
   printf '\n%s\n' "  --clean"
   printf '%s\n'   "    Removes files that are left in the /tmp/ directory when a call to --check"
   printf '%s\n'   "    finds differences."
@@ -110,7 +110,7 @@ set_output_file(){
   local config_file="$1"
 
   #Set the default output file path for the current config file.
-  OUTPUT_FILE="$SCRIPTDIR/test/data/configs/${config_file#*/configs/*}"
+  OUTPUT_FILE="$SCRIPTDIR/test/numerical/data/${config_file#*/numerical/*}"
   OUTPUT_FILE="${OUTPUT_FILE%.*}.output"
 
 }
@@ -137,10 +137,8 @@ run_config(){
   "$SCRIPTDIR/bin/nftsim" -i "$config_file" -o "$output_file"
   nftsim_status="$?"
 
-  #If the run was successful then gzip the resulting file.
-  if ((nftsim_status == 0)); then
-    gzip --force "$output_file"
-  else
+  #If the run was successful then print an error message.
+  if ((nftsim_status != 0)); then
     printf "$ERROR_CLR %s\n" "Failed running: $SCRIPTDIR/bin/nftsim -i $config_file -o $output_file"
   fi
   
@@ -148,14 +146,14 @@ run_config(){
 }
 
 get_all_config_files(){
-  #NOTE: currently restricting the search for conf files to a max-depth of 2 to avoid
-  #      running the conf files from Abeysuriya_2014, as they generate GB of output.
+  #NOTE: currently restricting the search for conf files to a max-depth of 1 as
+  #      we are placing all .conf files directly in the ./test/numerical/ directory.
   #SAK#requires BASH >=4.2# declare -ga CONFIG_FILES
-  CONFIG_FILES=($(find "$SCRIPTDIR/configs" -maxdepth 2 -type f -name '*.conf'))
+  CONFIG_FILES=($(find "$SCRIPTDIR/test/numerical" -maxdepth 1 -type f -name '*.conf'))
   return 0
 }
 
-#Creates an output file in ./test/data/configs/ corresponding to the specified .conf file.
+#Creates an output file in ./test/numerical/data/ corresponding to the specified .conf file.
 regenerate_output_file(){
   local config_file="$1"
   if [[ "$config_file" == "all" ]]; then
@@ -171,8 +169,8 @@ regenerate_output_file(){
     local -i regen_errors=0
     while read -r output_to_regenerate ; do
       regen_file="${output_to_regenerate##*/}"
-      regen_file="${regen_file%*.output.gz}"
-      regen_file="$(find "$SCRIPTDIR/configs" -maxdepth 3 -type f -name "${regen_file}.conf")"
+      regen_file="${regen_file%*.output}"
+      regen_file="$(find "$SCRIPTDIR/test/numerical" -maxdepth 1 -type f -name "${regen_file}.conf")"
       printf '%s\n' "Regenerating '$regen_file'..."
       set_output_file "$regen_file"
       if ! run_config "$regen_file"; then ((++regen_errors)); fi
@@ -184,7 +182,7 @@ regenerate_output_file(){
     return 0
   fi
   if [[ ! -f "$config_file" ]]; then
-    config_file="$(find "$SCRIPTDIR/configs" -maxdepth 3 -type f -name "${config_file}.conf")"
+    config_file="$(find "$SCRIPTDIR/test/numerical" -maxdepth 1 -type f -name "${config_file}.conf")"
   fi
   if [[ -f "$config_file" ]]; then
     set_output_file "$config_file"
@@ -193,7 +191,7 @@ regenerate_output_file(){
   else
     printf '%s\n' "You need to specify which config file to regenerate output for."
     printf '%s\n' "eg. nf_configs --regenerate 'example'"
-    printf '%s\n' "or nf_configs --regenerate './configs/example.conf'"
+    printf '%s\n' "or nf_configs --regenerate './test/numerical/example.conf'"
   fi
   return 1
 }
@@ -210,10 +208,10 @@ check_all(){
     if ! check_output_file "${CONFIG_FILES[i]}"; then ((++error_count)); fi
     if [[ "$DIFF_STATUS" = '0' ]]; then
       printf "output the ${SAME_CLR}.\n"
-      rm -f "${OUTPUT_FILE_TMP}.gz"
+      rm -f "${OUTPUT_FILE_TMP}"
     elif [[ "$DIFF_STATUS" = '1' ]]; then
       printf "output ${DIFFERS_CLR}\n"
-      printf '%s\n' "$(readlink -f "${OUTPUT_FILE}.gz")" >> "$changed_ouput_list"
+      printf '%s\n' "$(readlink -f "${OUTPUT_FILE}")" >> "$changed_ouput_list"
     fi
   done
   if [[ "$error_count" != '0' ]]; then
@@ -223,7 +221,7 @@ check_all(){
 }
 
 #Generates a temporary output file in /tmp/ for a specified config file and
-#compares it to the corresponding output file in nftsim/test/data/configs/
+#compares it to the corresponding output file in nftsim/test/numerical/data/
 check_output_file(){
   local config_file="$1"
   local config_file_name
@@ -231,19 +229,19 @@ check_output_file(){
 
   #If arg isn't a file, try mapping it to a file name.
   if [[ ! -f "$config_file" ]]; then
-    config_file="$(find "$SCRIPTDIR/configs" -maxdepth 3 -type f -name "${config_file}.conf")"
+    config_file="$(find "$SCRIPTDIR/test/numerical" -maxdepth 1 -type f -name "${config_file}.conf")"
   fi
 
   #Compare the current output of nftsim against stored output.
   if [[ -f "$config_file" ]]; then
     set_output_file "$config_file"
-    [[ -f "${OUTPUT_FILE}.gz" ]] || { printf "$ERROR_CLR %s\n" "No existing file to check against."; return 1; }
+    [[ -f "${OUTPUT_FILE}" ]] || { printf "$ERROR_CLR %s\n" "No existing file to check against."; return 1; }
     config_file_name="$(basename "$config_file")"
     #Path to file containing output of current nftsim.
     OUTPUT_FILE_TMP="$(mktemp --tmpdir="/tmp" --suffix=.output nftsim_"$config_file_name"-XXXX 2>/dev/null \
                      || mktemp /tmp/nftsim_"$config_file_name".XXXX)" #Alternative for OSX
     run_config "$config_file" "$OUTPUT_FILE_TMP" || return 1
-    diff -q <(zcat "${OUTPUT_FILE_TMP}.gz") <(zcat "${OUTPUT_FILE}.gz") &> /dev/null
+    diff -q "${OUTPUT_FILE_TMP}" "${OUTPUT_FILE}" &> /dev/null
     DIFF_STATUS="$?" #NOTE: No-diff = 0; diff = 1; error = 2
     return 0
   else
@@ -258,12 +256,12 @@ veiw_diff(){
   case "$DIFF_STATUS" in
     0)
       printf '%s\n' "'$config_file' output hasn't changed."
-      rm -f "${OUTPUT_FILE_TMP}.gz"
+      rm -f "${OUTPUT_FILE_TMP}"
   ;;
     1)
-      zdiff --side-by-side --suppress-common-lines --width=180 "${OUTPUT_FILE}.gz" "${OUTPUT_FILE_TMP}.gz" | less
+      diff --side-by-side --suppress-common-lines --width=180 "${OUTPUT_FILE}" "${OUTPUT_FILE_TMP}" | less
       printf '%s\n' "'$config_file' output DIFFERS!"
-      printf '%s\n' "See: '${OUTPUT_FILE_TMP}.gz'"
+      printf '%s\n' "See: '${OUTPUT_FILE_TMP}'"
   ;;
     2)
       printf '%s\n' "Error while running diff."
